// assume background is light blue
#ifndef BIRD_H
#define BIRD_H

#include <cstdint>
#define B_BLACK  0x0000
#define B_WHITE  0xffff
#define B_YELLOW 0b1111111000000111
#define B_ORANGE 0b1111001000100111

uint16_t bird_pix[10][10] = {
    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_WHITE, B_BLACK, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_BLACK, B_BLACK, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_WHITE, B_WHITE, B_WHITE, B_WHITE, B_YELLOW},

    {B_ORANGE, B_ORANGE, B_ORANGE, B_ORANGE, B_YELLOW, B_WHITE, B_WHITE, B_WHITE, B_WHITE, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_WHITE, B_WHITE, B_WHITE, B_WHITE, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},

    {B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW, B_YELLOW},
};

#endif